@BASE_URL = http://localhost:3000

### get deserts
GET {{BASE_URL}}/deserts
Content-Type: application/json


### post desert
POST {{BASE_URL}}/deserts
Content-Type: application/json

{
  "name": "Matcha Cake",
  "price": 140,
  "category": "cake"
}

### delete deserts
DELETE  {{BASE_URL}}/deserts/1
Content-Type: application/json