@BASE_URL = http://localhost:3000

### post review
POST {{BASE_URL}}/reviews
Content-Type: application/json

{
  "rating": 5,
  "comment": "อร่อยมาก",
  "dessertId": 1
}

### get deserts
GET {{BASE_URL}}/reviews/my
Content-Type: application/json

### delete deserts
DELETE  {{BASE_URL}}/reviews/1
Content-Type: application/json